package com.ezboost.model;

import java.sql.Timestamp;

/**
 * SeasonThreshold Model - Stores user-specific season classification thresholds
 * Generated by SeasonClassifierGA based on imported data
 */
public class SeasonThreshold {
    private int thresholdId;
    private int userId;
    private double thresholdLowNormal;      // Below this = LOW, above = NORMAL
    private double thresholdNormalPeak;     // Below this = NORMAL, above = PEAK
    private double thresholdPeakSuperPeak;  // Below this = PEAK, above = SUPER_PEAK
    private boolean isAutoGenerated;        // true if generated by GA, false if manual
    private Timestamp createdDate;
    private Timestamp lastUpdated;

    // Default constructor with standard thresholds
    public SeasonThreshold() {
        this.thresholdLowNormal = 65.0;
        this.thresholdNormalPeak = 75.0;
        this.thresholdPeakSuperPeak = 85.0;
        this.isAutoGenerated = false;
    }

    // Constructor with user ID and thresholds
    public SeasonThreshold(int userId, double t1, double t2, double t3, boolean isAutoGenerated) {
        this.userId = userId;
        this.thresholdLowNormal = t1;
        this.thresholdNormalPeak = t2;
        this.thresholdPeakSuperPeak = t3;
        this.isAutoGenerated = isAutoGenerated;
    }

    // Full constructor
    public SeasonThreshold(int thresholdId, int userId, double thresholdLowNormal,
                          double thresholdNormalPeak, double thresholdPeakSuperPeak,
                          boolean isAutoGenerated, Timestamp createdDate, Timestamp lastUpdated) {
        this.thresholdId = thresholdId;
        this.userId = userId;
        this.thresholdLowNormal = thresholdLowNormal;
        this.thresholdNormalPeak = thresholdNormalPeak;
        this.thresholdPeakSuperPeak = thresholdPeakSuperPeak;
        this.isAutoGenerated = isAutoGenerated;
        this.createdDate = createdDate;
        this.lastUpdated = lastUpdated;
    }

    /**
     * Classify an occupancy rate into a season based on these thresholds
     */
    public String classifyOccupancy(double occupancyRate) {
        if (occupancyRate < thresholdLowNormal) {
            return "LOW";
        } else if (occupancyRate < thresholdNormalPeak) {
            return "NORMAL";
        } else if (occupancyRate < thresholdPeakSuperPeak) {
            return "PEAK";
        } else {
            return "SUPER_PEAK";
        }
    }

    /**
     * Get the Season enum for an occupancy rate
     */
    public Season getSeasonEnum(double occupancyRate) {
        String seasonName = classifyOccupancy(occupancyRate);
        return Season.valueOf(seasonName);
    }

    /**
     * Validate that thresholds are in correct order
     */
    public boolean isValid() {
        return thresholdLowNormal < thresholdNormalPeak && 
               thresholdNormalPeak < thresholdPeakSuperPeak &&
               thresholdLowNormal > 0 &&
               thresholdPeakSuperPeak <= 100;
    }

    /**
     * Get threshold array for GA integration
     */
    public double[] getThresholdArray() {
        return new double[] { thresholdLowNormal, thresholdNormalPeak, thresholdPeakSuperPeak };
    }

    /**
     * Set thresholds from array (from GA output)
     */
    public void setFromArray(double[] thresholds) {
        if (thresholds != null && thresholds.length == 3) {
            this.thresholdLowNormal = thresholds[0];
            this.thresholdNormalPeak = thresholds[1];
            this.thresholdPeakSuperPeak = thresholds[2];
        }
    }

    // Getters and Setters
    public int getThresholdId() {
        return thresholdId;
    }

    public void setThresholdId(int thresholdId) {
        this.thresholdId = thresholdId;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public double getThresholdLowNormal() {
        return thresholdLowNormal;
    }

    public void setThresholdLowNormal(double thresholdLowNormal) {
        this.thresholdLowNormal = thresholdLowNormal;
    }

    public double getThresholdNormalPeak() {
        return thresholdNormalPeak;
    }

    public void setThresholdNormalPeak(double thresholdNormalPeak) {
        this.thresholdNormalPeak = thresholdNormalPeak;
    }

    public double getThresholdPeakSuperPeak() {
        return thresholdPeakSuperPeak;
    }

    public void setThresholdPeakSuperPeak(double thresholdPeakSuperPeak) {
        this.thresholdPeakSuperPeak = thresholdPeakSuperPeak;
    }

    public boolean isAutoGenerated() {
        return isAutoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        isAutoGenerated = autoGenerated;
    }

    public Timestamp getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Timestamp createdDate) {
        this.createdDate = createdDate;
    }

    public Timestamp getLastUpdated() {
        return lastUpdated;
    }

    public void setLastUpdated(Timestamp lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    @Override
    public String toString() {
        return "SeasonThreshold{" +
                "userId=" + userId +
                ", LOW < " + String.format("%.2f", thresholdLowNormal) + "%" +
                ", NORMAL: " + String.format("%.2f", thresholdLowNormal) + "-" + 
                              String.format("%.2f", thresholdNormalPeak) + "%" +
                ", PEAK: " + String.format("%.2f", thresholdNormalPeak) + "-" + 
                            String.format("%.2f", thresholdPeakSuperPeak) + "%" +
                ", SUPER_PEAK >= " + String.format("%.2f", thresholdPeakSuperPeak) + "%" +
                ", autoGenerated=" + isAutoGenerated +
                '}';
    }
}
