package com.ezboost.util;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.SQLException;
import java.sql.Statement;

/** Creates the original application tables only when a deployment starts with an empty database. */
final class CoreSchemaMigration {

    private CoreSchemaMigration() {
    }

    static void ensureCoreTables(Connection connection) throws SQLException {
        DatabaseMetaData metadata = connection.getMetaData();
        createIfMissing(connection, metadata, "USER", "CREATE TABLE \"USER\" (" +
                "UserID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, FirstName VARCHAR(100) NOT NULL, " +
                "LastName VARCHAR(100) NOT NULL, Username VARCHAR(255) NOT NULL, Email VARCHAR(320) NOT NULL, " +
                "Password VARCHAR(255) NOT NULL, PhoneNumber VARCHAR(50) NOT NULL, " +
                "Created_At TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, " +
                "Onboarding_Required BOOLEAN NOT NULL DEFAULT FALSE, Onboarding_Completed BOOLEAN NOT NULL DEFAULT TRUE, " +
                "Onboarding_Step VARCHAR(32) NOT NULL DEFAULT 'COMPLETE', Email_Key VARCHAR(320), Username_Key VARCHAR(255))");
        createIfMissing(connection, metadata, "ACTUALROOMDATA", "CREATE TABLE ActualRoomData (" +
                "RoomID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, UserID INT NOT NULL, RoomType VARCHAR(100) NOT NULL, " +
                "BaseADR DOUBLE NOT NULL, BaseADRWasBackfilled BOOLEAN NOT NULL DEFAULT FALSE, MinADR DOUBLE NOT NULL, " +
                "MaxADR DOUBLE NOT NULL, Occupancy DOUBLE NOT NULL, NumberOfRoom INT NOT NULL)");
        createIfMissing(connection, metadata, "MONTHLYSEASONDATA", "CREATE TABLE MonthlySeasonData (" +
                "DataID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, UserID INT NOT NULL, MonthYear VARCHAR(7) NOT NULL, " +
                "MonthName VARCHAR(20) NOT NULL, OccupancyRate DOUBLE NOT NULL, TotalRevenue DOUBLE NOT NULL, " +
                "AvgRoomRate DOUBLE NOT NULL, ClassifiedSeason VARCHAR(20) NOT NULL, " +
                "ImportDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)");
        createIfMissing(connection, metadata, "SEASONTHRESHOLD", "CREATE TABLE SeasonThreshold (" +
                "ThresholdID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, UserID INT NOT NULL, " +
                "ThresholdLowNormal DOUBLE NOT NULL, ThresholdNormalPeak DOUBLE NOT NULL, " +
                "ThresholdPeakSuperPeak DOUBLE NOT NULL, IsAutoGenerated BOOLEAN NOT NULL, " +
                "LastUpdated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)");
        createIfMissing(connection, metadata, "USERMULTIPLIERSETTINGS", "CREATE TABLE UserMultiplierSettings (" +
                "SettingID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, UserID INT NOT NULL, RoomType VARCHAR(100), " +
                "SeasonName VARCHAR(20) NOT NULL, SegmentName VARCHAR(100), CustomMultiplier DOUBLE NOT NULL, " +
                "MinBound DOUBLE NOT NULL, MaxBound DOUBLE NOT NULL, IsLocked BOOLEAN NOT NULL, " +
                "LastUpdated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)");
        createIfMissing(connection, metadata, "MARKETSEGMENT", "CREATE TABLE MarketSegment (" +
                "id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, user_id INT NOT NULL, segment_name VARCHAR(100) NOT NULL, " +
                "segment_code VARCHAR(20) NOT NULL, category VARCHAR(20) NOT NULL, rate_multiplier DOUBLE NOT NULL, " +
                "revenue_share DOUBLE NOT NULL DEFAULT 0, description VARCHAR(500), active BOOLEAN NOT NULL DEFAULT TRUE)");
        createIfMissing(connection, metadata, "OPTIMIZATIONREQUEST", "CREATE TABLE OptimizationRequest (" +
                "RequestID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, UserID INT NOT NULL, " +
                "RequestDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)");
        createIfMissing(connection, metadata, "OPTIMIZATIONRESULT", "CREATE TABLE OptimizationResult (" +
                "ResultID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, RequestID INT NOT NULL, RoomType VARCHAR(100) NOT NULL, " +
                "NumberofRoom INT NOT NULL, ExpectedOccupancyRate DOUBLE NOT NULL, LowSeasonPrice DOUBLE NOT NULL, " +
                "NormalSeasonPrice DOUBLE NOT NULL, PeakSeasonPrice DOUBLE NOT NULL, SuperPeakSeasonPrice DOUBLE NOT NULL, " +
                "EstimatedProfit DOUBLE NOT NULL, TotalEstimatedProfit DOUBLE NOT NULL)");
    }

    private static void createIfMissing(Connection connection, DatabaseMetaData metadata, String tableName, String ddl)
            throws SQLException {
        try (java.sql.ResultSet tables = metadata.getTables(null, DerbySchema.current(metadata), tableName, new String[]{"TABLE"})) {
            if (tables.next()) return;
        }
        try (Statement statement = connection.createStatement()) {
            statement.executeUpdate(ddl);
        }
    }
}
